global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'captcha-service'
    static_configs:
      - targets: ['captcha-service:9090']
    scrape_interval: 5s
    metrics_path: /metrics
    scheme: http

  - job_name: 'captcha-service-security'
    static_configs:
      - targets: ['captcha-service:9090']
    scrape_interval: 30s
    metrics_path: /security/stats
    scheme: http
